server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
