server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  h2:
    console:
      enabled: ${convertfactorms.h2.console.enabled}
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${convertfactorms.datasource.url}
    username: ${convertfactorms.datasource.username}
    password: ${convertfactorms.datasource.password}
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop        
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
        
        
