server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\kolkata2020labsconfig
          uri: https://github.com/paulsan1/microservice.git
          username: paulsan1@in.ibm.com
          password: P@ssw0rd@IBM
          skipSslValidation: true  
    bus:
      enabled: true
      destination: configXchangebus                   
  rabbitmq:
    host: 192.168.99.100
    port: 5672
       
